import assert from 'node:assert/strict';
import { spawnSync } from 'node:child_process';
import { createHash } from 'node:crypto';
import { mkdtemp, mkdir, writeFile, readFile, rm } from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import test from 'node:test';
import { fileURLToPath } from 'node:url';
import { z } from 'zod';
import { canonicalRoot, discover } from '../src/git/discovery.js';
import { resolveLimits, type Config } from '../src/config/schema.js';
import { collectRepository } from '../src/git/collector.js';
import { runGit, type GitRunner } from '../src/git/runner.js';
import { patchOptions, type Scope } from '../src/git/adapter.js';
import { buildBundle } from '../src/evidence/bundle.js';
import { extendSyntaxBundle } from '../src/evidence/syntax.js';
import { extendCandidateBundle } from '../src/candidates/collect.js';
import { discoveryDefaults, type CorpusFile } from '../src/candidates/contracts.js';
import { CandidateSearch, runRg, type RgRunner } from '../src/candidates/rg.js';
import { candidateOutputSchema, candidateId, validateCandidateBundle } from '../src/evidence/candidates.js';
import { renderContext } from '../src/output/context.js';

const limits = resolveLimits(undefined), config: Config = { configVersion: '1' }, entrypoint = fileURLToPath(new URL('../../dist/cli/main.js', import.meta.url));
const hash = (bytes: Buffer | string) => createHash('sha256').update(bytes).digest('hex');
function git(root: string, ...args: string[]) { const result = spawnSync('git', ['-c', 'core.autocrlf=false', '-c', 'user.name=Synthetic', '-c', 'user.email=fixture@example.invalid', '-c', 'commit.gpgSign=false', ...args], { cwd: root, env: Object.fromEntries(Object.entries(process.env).filter(([key]) => !key.toUpperCase().startsWith('GIT_'))), shell: false, timeout: 30000 }); assert.ifError(result.error); assert.equal(result.status, 0, result.stderr.toString()); return result.stdout; }
async function initialize(root: string) { await mkdir(root, { recursive: true }); git(root, 'init', '-b', 'main'); git(root, 'config', 'core.autocrlf', 'false'); await writeFile(path.join(root, '.git', 'fixture-ignore'), ''); await writeFile(path.join(root, '.git', 'fixture-attributes'), ''); git(root, 'config', 'core.excludesFile', '.git/fixture-ignore'); git(root, 'config', 'core.attributesFile', '.git/fixture-attributes'); }
async function fixture(fn: (root: string) => Promise<void>) { const root = await mkdtemp(path.join(os.tmpdir(), 'difflearn-candidate-')); try { await initialize(root); await fn(root); } finally { assert.equal(path.dirname(root), os.tmpdir()); await rm(root, { recursive: true, force: true }); } }
async function baseline(root: string, name = 'sample.ts') { await writeFile(path.join(root, name), 'export function duplicate() { return 1; }\n'); git(root, 'add', '.'); git(root, 'commit', '-m', 'synthetic baseline'); git(root, 'branch', 'baseline'); }
async function setup(root: string, scope: Scope = 'staged', customConfig = config) {
  const actual = await canonicalRoot(root), found = await discover(actual, customConfig, limits), budget = { workspaceBytes: 0 }; const repositories = [];
  for (const repository of found.repositories) repositories.push(await collectRepository(repository, customConfig, limits, budget, 'baseline', undefined, runGit, { scope, includeUntracked: false, symbols: true }));
  const time = '2026-10-04T00:00:00.000Z'; const base = buildBundle({ collector: { name: 'difflearn', version: 'fixture', gitVersion: 'fixture' }, collection: { startedAt: time, endedAt: time }, request: { root: actual, configPath: null, repositories: [], base: 'baseline', scopes: [scope], contentPolicy: 'metadata-only', comparisonOptions: patchOptions, immutableAttributeSource: 'captured-head', limits }, discovery: found.discovery, repositories, diagnostics: repositories.flatMap(repo => repo.diagnostics), discoveryCompleteness: found.completeness });
  return { repositories, budget, syntax: extendSyntaxBundle(base, repositories), customConfig };
}
async function extend(input: Awaited<ReturnType<typeof setup>>, request = { ...discoveryDefaults, references: true, relatedTests: true, history: true }, rg: RgRunner = runRg, runner: GitRunner = runGit) { return extendCandidateBundle(input.syntax, input.repositories, input.customConfig, limits, input.budget, request, 'baseline', undefined, runner, rg); }
function cli(root: string, command = 'evidence', ...args: string[]) { const result = spawnSync(process.execPath, [entrypoint, command, '--root', root, '--base', 'baseline', '--scope', 'staged', ...args], { shell: false, encoding: 'utf8', timeout: 120000, maxBuffer: 16 * 1024 * 1024 }); assert.ifError(result.error); return result; }

test('fixed-string structured search distinguishes no matches, missing rg, errors and both result/output limits', async () => {
  const bytes = Buffer.from('// duplicate duplicate\nconst value = "duplicate";\n'); const content: CorpusFile = { bytes, snapshot: { repositoryId: '1'.repeat(64), snapshotId: '2'.repeat(64), comparisonId: '3'.repeat(64), corpusId: '4'.repeat(64), path: 'sample ไทย.ts', pathBytes: Buffer.from('sample ไทย.ts').toString('base64'), origin: 'filesystem', endpoint: 'working-tree', oid: null, sha256: hash(bytes), byteLength: bytes.length } };
  const search = await CandidateSearch.create([content], 1024 * 1024, 10000);
  try { const none = await search.search('absent', 20); assert.equal(none.outcome, 'no-matches'); const limited = await search.search('duplicate', 1); assert.equal(limited.outcome, 'truncated'); assert.equal(limited.matches.length, 1); assert.equal(limited.omittedMatches, null); assert.ok(limited.arguments.includes('--fixed-strings')); assert.ok(limited.arguments.includes('--no-config')); for (const match of limited.matches) assert.equal(bytes.subarray(match.startByte, match.endByte).toString(), 'duplicate'); const literal = await search.search('.*', 20); assert.equal(literal.outcome, 'no-matches'); } finally { await search.dispose(); }
  for (const [failure, outcome] of [['missing-rg', 'missing-rg'], ['execution-error', 'execution-error']] as const) { const fake: RgRunner = async () => ({ code: null, stdout: Buffer.alloc(0), stderr: '', failure, truncated: false }); const item = await CandidateSearch.create([content], 1000, 1000, undefined, fake); try { assert.equal((await item.search('duplicate', 20)).outcome, outcome); } finally { await item.dispose(); } }
  const bounded = await CandidateSearch.create([content], 16, 10000); try { const result = await bounded.search('duplicate', 20); assert.equal(result.outcome, 'truncated'); assert.equal(result.matches.length, 0); } finally { await bounded.dispose(); }
});

test('scope after endpoints use exact HEAD/index/working bytes and preserve syntax/Git evidence', async () => fixture(async root => {
  await baseline(root); await writeFile(path.join(root, 'peer.ts'), '// duplicate HEAD\n'); git(root, 'add', '.'); git(root, 'commit', '-m', 'synthetic peer'); await writeFile(path.join(root, 'sample.ts'), 'export function duplicate() { return 2; }\n'); git(root, 'commit', '-am', 'synthetic committed symbol'); await writeFile(path.join(root, 'peer.ts'), '// duplicate INDEX\n'); await writeFile(path.join(root, 'sample.ts'), 'export function duplicate() { return 3; }\n'); git(root, 'add', '.'); await writeFile(path.join(root, 'peer.ts'), '// duplicate WORK\n'); await writeFile(path.join(root, 'sample.ts'), 'export function duplicate() { return 4; }\n');
  for (const [scope, expected, origin] of [['branch', '// duplicate HEAD\n', 'git-blob'], ['staged', '// duplicate INDEX\n', 'git-blob'], ['unstaged', '// duplicate WORK\n', 'filesystem'], ['all', '// duplicate WORK\n', 'filesystem']] as const) {
    const input = await setup(root, scope), bundle = await extend(input, { ...discoveryDefaults, references: true, relatedTests: false, history: false }); assert.equal(bundle.discoveryAnalysis.references.state, 'complete', JSON.stringify({ scope, analysis: bundle.discoveryAnalysis, diagnostics: bundle.diagnostics }));
    const peer = bundle.discoveryAnalysis.corpus.files.find(file => file.path === 'peer.ts')!; assert.equal(peer.sha256, hash(expected)); assert.equal(peer.origin, origin);
    assert.deepEqual(bundle.evidence.filter(entry => ['repository', 'comparison', 'file-change', 'hunk', 'untracked-file', 'conflict', 'symbol', 'language-analysis'].includes(entry.kind)), input.syntax.evidence);
    const refs = bundle.evidence.filter(entry => entry.kind === 'reference-candidate' && entry.data.location.content.path === 'peer.ts'); assert.ok(refs.length); for (const entry of refs) { assert.equal(entry.confidence, 'candidate'); assert.equal(entry.data.interpretation, 'text-match-not-confirmed-reference'); assert.equal(Buffer.from(expected).subarray(entry.data.location.startByte, entry.data.location.endByte).toString(), 'duplicate'); }
  }
}));

test('same-name symbols across repos, comments/strings, workspace bounds and excludes remain only candidates', async () => fixture(async root => {
  const workspace = path.join(root, 'workspace'), first = path.join(workspace, 'first'), sibling = path.join(workspace, 'sibling ไทย'), nested = path.join(workspace, 'nested');
  for (const repo of [first, sibling, nested]) { await initialize(repo); await baseline(repo); await writeFile(path.join(repo, 'sample.ts'), 'export function duplicate() { return 2; }\n'); await writeFile(path.join(repo, 'peer.ts'), '// duplicate\nconst text = "duplicate";\n'); await mkdir(path.join(repo, 'node_modules')); await writeFile(path.join(repo, 'node_modules', 'excluded.ts'), '// duplicate\n'); await mkdir(path.join(repo, 'skip')); await writeFile(path.join(repo, 'skip', 'ignored.ts'), '// duplicate\n'); git(repo, 'add', '.'); }
  const customConfig: Config = { configVersion: '1', excludeDirectories: ['skip'], excludePaths: ['nested/peer.ts'] }; const input = await setup(workspace, 'staged', customConfig), bundle = await extend(input, { ...discoveryDefaults, references: true, relatedTests: false, history: false });
  const references = bundle.evidence.filter(entry => entry.kind === 'reference-candidate'); assert.ok(references.some(entry => entry.data.crossRepository)); assert.ok(references.some(entry => entry.data.location.content.path === 'peer.ts' && entry.data.location.line === 1)); assert.ok(references.some(entry => entry.data.location.content.path === 'peer.ts' && entry.data.location.line === 2)); assert.ok(!bundle.discoveryAnalysis.corpus.files.some(file => file.path.startsWith('skip/') || file.path.startsWith('node_modules/') || file.path.startsWith('nested/') || file.path.startsWith('sibling ไทย/')));
  const nestedId = input.repositories.find(repo => repo.path === 'nested')!.repositoryId; assert.ok(!bundle.discoveryAnalysis.corpus.files.some(file => file.repositoryId === nestedId && file.path === 'peer.ts')); assert.ok(bundle.evidence.filter(entry => entry.kind === 'reference-query').filter(entry => entry.data.query === 'duplicate').every(entry => entry.data.sameNameSymbolIds.length >= 6));
}));

test('potential tests explain filename, text, relative import and test-call syntax without running anything', async () => fixture(async root => {
  await mkdir(path.join(root, 'src')); await baseline(root, 'src/sample.ts'); await mkdir(path.join(root, 'tests')); await writeFile(path.join(root, 'tests', 'sample.test.ts'), 'import { duplicate as alias } from "../src/sample";\nit("synthetic", () => alias());\n'); await writeFile(path.join(root, 'tests', 'notes.test.ts'), '// duplicate appears only in a comment\n'); await writeFile(path.join(root, 'unusual.ts'), 'import { duplicate as alias } from "./src/sample";\ntest("synthetic", () => alias());\n'); await writeFile(path.join(root, 'tests', 'unrelated.test.ts'), 'it("other", () => 0);\n'); git(root, 'add', '.'); git(root, 'commit', '-m', 'synthetic potential tests'); await writeFile(path.join(root, 'src', 'sample.ts'), 'export function duplicate() { return 2; }\n'); git(root, 'add', '.');
  // A marker would be created if any repository script/hook/test were run.
  await writeFile(path.join(root, '.git', 'hooks', 'pre-commit'), '#!/bin/sh\ntouch forbidden-marker\n'); await writeFile(path.join(root, 'package.json'), JSON.stringify({ scripts: { test: 'node -e "require(\"fs\").writeFileSync(\"forbidden-marker\",\"bad\")"' } }));
  const bundle = await extend(await setup(root)); const tests = bundle.evidence.filter(entry => entry.kind === 'related-test-candidate'); assert.ok(tests.some(entry => entry.data.content.path === 'tests/sample.test.ts' && entry.data.heuristic.includes('relative-import-syntax') && entry.data.heuristic.includes('same-file-stem'))); assert.ok(tests.some(entry => entry.data.content.path === 'tests/notes.test.ts' && entry.data.heuristic.includes('fixed-string-symbol-text'))); assert.ok(tests.some(entry => entry.data.content.path === 'unusual.ts' && entry.data.heuristic.includes('test-call-syntax'))); assert.ok(!tests.some(entry => entry.data.content.path === 'tests/unrelated.test.ts')); assert.ok(tests.every(entry => entry.data.testExecution === 'not-run' && entry.confidence === 'candidate')); await assert.rejects(readFile(path.join(root, 'forbidden-marker')));
  const limited = await extend(await setup(root), { ...discoveryDefaults, maxResults: 1, references: false, relatedTests: true, history: false }); assert.equal(limited.discoveryAnalysis.relatedTests.state, 'partial'); assert.ok(limited.discoveryAnalysis.relatedTests.reasons.includes('RELATED_TEST_RESULT_LIMIT'));
}));

test('missing rg and execution errors remain observable while history and Git facts survive', async () => fixture(async root => {
  await baseline(root); await writeFile(path.join(root, 'sample.ts'), 'export function duplicate() { return 2; }\n'); git(root, 'add', '.');
  for (const failure of ['missing-rg', 'execution-error'] as const) { const fake: RgRunner = async () => ({ code: null, stdout: Buffer.alloc(0), stderr: 'synthetic failure', failure, truncated: false }); const bundle = await extend(await setup(root), undefined, fake); assert.equal(bundle.completeness.state, 'partial'); assert.ok(bundle.evidence.some(entry => entry.kind === 'file-change')); assert.ok(bundle.evidence.some(entry => entry.kind === 'reference-query' && entry.data.outcome === failure)); assert.ok(bundle.evidence.some(entry => entry.kind === 'history' && entry.data.commits.length)); assert.ok(bundle.diagnostics.some(item => item.code === (failure === 'missing-rg' ? 'RG_MISSING' : 'RG_EXECUTION_ERROR'))); }
}));

test('literal path history uses pinned HEAD, precise Git query and N+1 bounds; unborn history is empty', async () => fixture(async root => {
  const filename = 'sample [x] ไทย.ts'; await baseline(root, filename); for (let value = 2; value < 5; value++) { await writeFile(path.join(root, filename), `export function duplicate() { return ${value}; }\n`); git(root, 'commit', '-am', `synthetic message ${value}; no behavior claim`); }
  await writeFile(path.join(root, filename), 'export function duplicate() { return 5; }\n'); git(root, 'add', '.'); git(root, 'config', 'log.follow', 'true'); git(root, 'config', 'log.abbrevCommit', 'true'); git(root, 'config', 'color.ui', 'always'); const bundle = await extend(await setup(root), { ...discoveryDefaults, maxHistory: 2, references: false, relatedTests: false, history: true });
  const history = bundle.evidence.find(entry => entry.kind === 'history')!; assert.equal(history.kind, 'history'); if (history.kind !== 'history') return; assert.equal(history.data.outcome, 'truncated'); assert.ok(history.data.reasons.includes('HISTORY_RESULT_LIMIT')); assert.equal(history.data.commits.length, 2); const oracle = git(root, '--literal-pathspecs', '-c', 'log.follow=false', 'log', '--topo-order', '--max-count=3', '--format=%H', history.data.headOid!, '--', filename).toString().trim().split('\n').slice(0, 2); assert.deepEqual(history.data.commits.map(commit => commit.oid), oracle); assert.deepEqual(history.data.paths, [filename]); assert.ok(history.data.arguments.includes('--end-of-options')); assert.ok(history.data.arguments.includes('log.follow=false')); assert.ok(history.data.arguments.includes('--no-use-mailmap')); assert.equal(history.data.runtimeBehavior, 'not-inferred'); assert.ok(!JSON.stringify(history.data).includes('synthetic message'));
  git(root, 'mv', '--', filename, 'renamed.ts'); git(root, 'commit', '-m', 'synthetic rename'); const renameOid = git(root, 'rev-parse', 'HEAD').toString().trim(); await writeFile(path.join(root, 'renamed.ts'), 'export function duplicate() { return 6; }\n'); git(root, 'add', '.');
  const renamed = await extend(await setup(root), { ...discoveryDefaults, references: false, relatedTests: false, history: true }); const lineage = renamed.evidence.find(entry => entry.kind === 'history')!; assert.equal(lineage.kind, 'history'); if (lineage.kind === 'history') assert.deepEqual(lineage.data.commits.map(commit => commit.oid), [renameOid], 'literal destination history must not follow the prior file name even with log.follow=true');
  await writeFile(path.join(root, '.git', 'shallow'), `${renameOid}\n`); const shallow = await extend(await setup(root), { ...discoveryDefaults, references: false, relatedTests: false, history: true }); assert.ok(shallow.discoveryAnalysis.history.reasons.includes('HISTORY_SHALLOW')); assert.ok(shallow.evidence.some(entry => entry.kind === 'history' && entry.data.shallow));
  const unborn = path.join(root, 'unborn'); await initialize(unborn); await writeFile(path.join(unborn, 'new.ts'), 'export const added = () => 1;\n'); git(unborn, 'add', '.'); const empty = await extend(await setup(unborn), { ...discoveryDefaults, references: false, relatedTests: false, history: true }); assert.ok(empty.evidence.some(entry => entry.kind === 'history' && entry.data.outcome === 'unborn' && entry.data.headOid === null && entry.data.commits.length === 0));
}));

test('changed working snapshots withhold candidates, history errors and query limits disclose partial coverage', async () => fixture(async root => {
  await baseline(root); await writeFile(path.join(root, 'sample.ts'), 'export function duplicate() { return 2; }\n'); const input = await setup(root, 'unstaged'); await writeFile(path.join(root, 'sample.ts'), 'export function duplicate() { return 3; }\n'); const changed = await extend(input, { ...discoveryDefaults, references: true, relatedTests: false, history: false }); assert.ok(changed.discoveryAnalysis.references.reasons.includes('CANDIDATE_SNAPSHOT_CHANGED')); assert.equal(changed.evidence.filter(entry => entry.kind === 'reference-candidate').length, 0); assert.ok(changed.evidence.some(entry => entry.kind === 'symbol'));
  git(root, 'add', '.'); const limited = await extend(await setup(root), { ...discoveryDefaults, maxSymbols: 1, references: true, relatedTests: false, history: false }); assert.equal(limited.discoveryAnalysis.references.omittedQueries, 1); assert.ok(limited.diagnostics.some(item => item.code === 'CANDIDATE_SYMBOL_LIMIT'));
  const broken: GitRunner = async (...args) => args[1].includes('log') ? { code: 128, stdout: Buffer.alloc(0), stderr: 'synthetic history failure' } : runGit(...args); const failed = await extend(await setup(root), { ...discoveryDefaults, references: false, relatedTests: false, history: true }, runRg, broken); assert.ok(failed.evidence.some(entry => entry.kind === 'history' && entry.data.outcome === 'execution-error')); assert.equal(failed.discoveryAnalysis.history.state, 'partial');
}));

test('CLI emits one English-keyed validated document, stable IDs/localized cited context, and preserves defaults', async () => fixture(async root => {
  await baseline(root); await writeFile(path.join(root, 'sample.ts'), 'export function duplicate() { return 2; }\n'); git(root, 'add', '.'); const plain = cli(root); assert.equal(plain.status, 0); assert.equal(JSON.parse(plain.stdout).schemaVersion, '1.0.0'); const en = cli(root, 'evidence', '--references', '--related-tests', '--history', '--json', '--lang', 'en'), th = cli(root, 'evidence', '--references', '--related-tests', '--history', '--json', '--lang', 'th'); assert.equal(en.status, 0, en.stderr); assert.equal(th.status, 0, th.stderr); assert.equal(en.stdout.trim().split('\n').length, 1); const bundle = validateCandidateBundle(JSON.parse(en.stdout)), other = validateCandidateBundle(JSON.parse(th.stdout)); assert.deepEqual(bundle.evidence.map(entry => entry.id), other.evidence.map(entry => entry.id)); assert.equal(bundle.schemaVersion, '1.2.0');
  const context = renderContext(bundle, 'en').markdown; assert.match(context, /not confirm callers or dependencies/u); assert.match(context, /missing test nor a coverage gap/u); for (const entry of bundle.evidence) assert.ok(context.includes(`evidence:${entry.id}`)); const thai = cli(root, 'context', '--references', '--related-tests', '--history', '--lang', 'th'); assert.equal(thai.status, 0, thai.stderr); assert.match(thai.stdout, /ยังไม่รัน/u);
  const tampered = structuredClone(bundle); const ref = tampered.evidence.find(entry => entry.kind === 'reference-candidate')!; if (ref.kind === 'reference-candidate') { ref.data.location.content.sha256 = '0'.repeat(64); ref.id = candidateId(ref); } assert.throws(() => validateCandidateBundle(tampered), { code: 'INTERNAL_CONTRACT_ERROR' });
  const invalid = cli(root, 'evidence', '--references', '--max-results', '0'); assert.equal(invalid.status, 2); assert.equal(JSON.parse(invalid.stdout).reportKind, 'error');
}));

test('candidate schema is versioned independently and matches generated JSON schema', async () => { const schema = JSON.parse(await readFile(new URL('../../docs/candidate-evidence.schema.json', import.meta.url), 'utf8')); assert.deepEqual(schema, z.toJSONSchema(candidateOutputSchema, { target: 'draft-2020-12', io: 'input' })); });
