import assert from 'node:assert/strict';
import { spawnSync } from 'node:child_process';
import { createHash } from 'node:crypto';
import { mkdtemp, writeFile, readFile, rm } from 'node:fs/promises';
import path from 'node:path';
import os from 'node:os';
import test from 'node:test';
import { fileURLToPath } from 'node:url';
import { z } from 'zod';
import { canonicalRoot, discover } from '../src/git/discovery.js';
import { resolveLimits } from '../src/config/schema.js';
import { collectRepository } from '../src/git/collector.js';
import { runGit, type GitRunner } from '../src/git/runner.js';
import { patchOptions, type Scope } from '../src/git/adapter.js';
import { buildBundle } from '../src/evidence/bundle.js';
import { extendSyntaxBundle, validateSyntaxBundle, syntaxId, syntaxOutputSchema } from '../src/evidence/syntax.js';
import { TreeSitterAnalyzer } from '../src/language/tree-sitter.js';
import { renderContext } from '../src/output/context.js';

const hash = (bytes: Buffer | string) => createHash('sha256').update(bytes).digest('hex');
const limits = resolveLimits(undefined); const config = { configVersion: '1' as const }; const entrypoint = fileURLToPath(new URL('../../dist/cli/main.js', import.meta.url));
function git(root: string, ...args: string[]) { const result = spawnSync('git', ['-c', 'core.autocrlf=false', '-c', 'user.name=Synthetic', '-c', 'user.email=fixture@example.invalid', '-c', 'commit.gpgSign=false', ...args], { cwd: root, env: Object.fromEntries(Object.entries(process.env).filter(([key]) => !key.toUpperCase().startsWith('GIT_'))), shell: false, timeout: 30000 }); assert.ifError(result.error); assert.equal(result.status, 0, result.stderr.toString()); return result.stdout; }
async function fixture(fn: (root: string) => Promise<void>) { const root = await mkdtemp(path.join(os.tmpdir(), 'difflearn-language-')); try { git(root, 'init', '-b', 'main'); git(root, 'config', 'core.autocrlf', 'false'); await writeFile(path.join(root, '.git', 'fixture-ignore'), ''); await writeFile(path.join(root, '.git', 'fixture-attributes'), ''); git(root, 'config', 'core.excludesFile', '.git/fixture-ignore'); git(root, 'config', 'core.attributesFile', '.git/fixture-attributes'); await fn(root); } finally { await rm(root, { recursive: true, force: true }); } }
async function commit(root: string, filename: string, content: string) { await writeFile(path.join(root, filename), content); git(root, 'add', '.'); git(root, 'commit', '-m', 'synthetic baseline'); git(root, 'branch', 'baseline'); }
async function collect(root: string, scope: Scope = 'staged', runner: GitRunner = runGit) {
  const actual = await canonicalRoot(root); const found = await discover(actual, config, limits); const repository = await collectRepository(found.repositories[0]!, config, limits, { workspaceBytes: 0 }, 'baseline', undefined, runner, { scope, includeUntracked: false, symbols: true });
  const time = '2026-10-04T00:00:00.000Z'; const base = buildBundle({ collector: { name: 'difflearn', version: 'fixture', gitVersion: 'fixture' }, collection: { startedAt: time, endedAt: time }, request: { root: actual, configPath: null, repositories: [], base: 'baseline', scopes: [scope], contentPolicy: 'metadata-only', comparisonOptions: patchOptions, immutableAttributeSource: 'captured-head', limits }, discovery: found.discovery, repositories: [repository], diagnostics: repository.diagnostics, discoveryCompleteness: found.completeness });
  return { repository, base, bundle: extendSyntaxBundle(base, [repository]) };
}
function cli(root: string, command: 'evidence' | 'context', ...args: string[]) { const result = spawnSync(process.execPath, [entrypoint, command, '--root', root, '--base', 'baseline', '--scope', 'staged', ...args], { encoding: 'utf8', shell: false, timeout: 90_000, maxBuffer: 16 * 1024 * 1024 }); assert.ifError(result.error); return result; }

test('pinned runtime loads ABI-14 TS/TSX/JS grammars on the declared Node baseline', async () => {
  const analyzer = new TreeSitterAnalyzer(); assert.equal(analyzer.capabilities.runtime, '0.21.1'); assert.equal(analyzer.capabilities.semanticReferences, false); assert.equal(analyzer.languageForPath('a.tsx'), 'tsx'); assert.equal(analyzer.languageForPath('a.mjs'), 'javascript'); assert.equal(analyzer.languageForPath('a.py'), null);
  const api = await readFile(new URL('../../node_modules/tree-sitter/vendor/tree-sitter/lib/include/tree_sitter/api.h', import.meta.url), 'utf8'); assert.match(api, /TREE_SITTER_LANGUAGE_VERSION 14/u); assert.match(api, /TREE_SITTER_MIN_COMPATIBLE_LANGUAGE_VERSION 13/u);
  for (const filename of ['tree-sitter-typescript/typescript/src/parser.c', 'tree-sitter-typescript/tsx/src/parser.c', 'tree-sitter-javascript/src/parser.c']) assert.match((await readFile(new URL('../../node_modules/' + filename, import.meta.url), 'utf8')).slice(0, 1000), /LANGUAGE_VERSION 14/u);
});

test('all scopes analyze exact blob/index/captured working sources; Git facts survive syntax extension unchanged', async () => fixture(async root => {
  const source = (value: string) => `export function sample() {\n  return "${value}";\n}\n`; const before = source('base'); await commit(root, 'sample.ts', before); await writeFile(path.join(root, 'sample.ts'), source('head')); git(root, 'commit', '-am', 'synthetic committed change'); await writeFile(path.join(root, 'sample.ts'), source('index')); git(root, 'add', '.'); await writeFile(path.join(root, 'sample.ts'), source('working'));
  for (const [scope, old, fresh] of [['branch', 'base', 'head'], ['staged', 'head', 'index'], ['unstaged', 'index', 'working'], ['all', 'base', 'working']] as const) {
    const { repository, base, bundle } = await collect(root, scope); assert.equal(repository.state, 'complete', JSON.stringify({ scope, reasons: repository.reasons, diagnostics: repository.diagnostics })); assert.equal(bundle.languageAnalysis.state, 'complete', JSON.stringify(bundle.languageAnalysis)); const result = repository.comparisons[0]!.files[0]!.languageAnalysis!;
    assert.deepEqual(result.sources.map(item => item.sha256), [hash(source(old)), hash(source(fresh))]); assert.equal(result.sources[1]?.origin, scope === 'branch' || scope === 'staged' ? 'git-blob' : 'filesystem'); assert.equal(result.sources[1]?.oid === null, scope === 'unstaged' || scope === 'all');
    const symbols = bundle.evidence.filter(entry => entry.kind === 'symbol'); assert.equal(symbols.length, 2); for (const symbol of symbols) { assert.equal(symbol.data.name, 'sample'); assert.equal(symbol.data.matching, 'candidate'); const content = Buffer.from(source(symbol.data.side === 'before' ? old : fresh)); assert.equal(symbol.data.contentHash, hash(content.subarray(symbol.data.range.startByte, symbol.data.range.endByte))); }
    assert.deepEqual(bundle.evidence.filter(entry => entry.kind !== 'symbol' && entry.kind !== 'language-analysis'), base.evidence); assert.equal(bundle.schemaVersion, '1.1.0'); assert.equal(base.schemaVersion, '1.0.0');
  }
}));

test('hunks map multiple declarations, class/method scopes, exports/arrows/types, imports and top-level changes with byte ranges', async () => fixture(async root => {
  const old = 'import { old } from "module";\nexport class Old {\n  method() { return 1; }\n}\nexport function kept() { return 1; }\nexport const arrow = () => 1;\ntype Shape = { value: number };\ninterface Model { value: number; }\nconst gone = () => 0;\nconst a = () => 1; const b = () => 2;\nconsole.log("old");\nexport const ชื่อ = () => "😀";\n';
  const fresh = old.replace('{ old }', '{ fresh }').replace('class Old', 'class New').replaceAll('return 1', 'return 2').replace('arrow = () => 1', 'arrow = () => 2').replaceAll('value: number', 'value: string').replace('const gone = () => 0;\n', '').replace('a = () => 1; const b = () => 2', 'a = () => 3; const b = () => 4').replace('console.log("old")', 'console.log("new")').replace('"😀"', '"ไทย😀"');
  await commit(root, 'sample.ts', old); await writeFile(path.join(root, 'sample.ts'), fresh); git(root, 'add', '.'); const { bundle } = await collect(root); assert.equal(bundle.languageAnalysis.state, 'complete');
  const symbols = bundle.evidence.filter(entry => entry.kind === 'symbol'); for (const kind of ['class', 'method', 'function', 'arrow-function', 'type-alias', 'interface', 'import', 'top-level']) assert.ok(symbols.some(entry => entry.data.kind === kind), kind);
  assert.ok(symbols.some(entry => entry.data.name === 'gone' && entry.data.side === 'before' && entry.data.matching === 'unmatched')); assert.ok(!symbols.some(entry => entry.data.name === 'gone' && entry.data.side === 'after')); assert.ok(symbols.some(entry => entry.data.kind === 'method' && entry.data.scope.some(scope => scope.name === 'New')));
  for (const name of ['a', 'b', 'ชื่อ']) assert.ok(symbols.some(entry => entry.data.name === name)); assert.ok(new Set(symbols.flatMap(entry => entry.data.hunkEvidenceIds)).size < symbols.length);
  assert.ok(symbols.filter(entry => entry.data.kind === 'class').every(entry => entry.data.matching === 'unmatched' && entry.data.counterpartOrdinal === null));
  for (const entry of symbols) { const content = Buffer.from(entry.data.side === 'before' ? old : fresh); assert.equal(hash(content.subarray(entry.data.range.startByte, entry.data.range.endByte)), entry.data.contentHash); }
}));

test('TSX and JavaScript declarations use only their selected grammar; renamed files retain source sides', async () => fixture(async root => {
  await commit(root, 'view.tsx', 'export const View = () => (\n  <main>\n    old\n  </main>\n);\n'); await writeFile(path.join(root, 'sample.js'), 'export function js() { return 1; }\n'); git(root, 'add', '.'); git(root, 'commit', '-m', 'synthetic JavaScript'); git(root, 'mv', 'view.tsx', 'renamed.tsx'); await writeFile(path.join(root, 'renamed.tsx'), 'export const View = () => (\n  <main>\n    new\n  </main>\n);\n'); await writeFile(path.join(root, 'sample.js'), 'export function js() { return 2; }\n'); git(root, 'add', '.');
  const { bundle } = await collect(root); assert.equal(bundle.languageAnalysis.state, 'complete'); assert.ok(bundle.evidence.some(entry => entry.kind === 'symbol' && entry.data.language === 'tsx' && entry.data.name === 'View')); assert.ok(bundle.evidence.some(entry => entry.kind === 'symbol' && entry.data.language === 'javascript' && entry.data.name === 'js'));
  const renamed = bundle.evidence.find(entry => entry.kind === 'file-change' && entry.data.status === 'R')!; assert.ok(renamed); const analysis = bundle.evidence.find(entry => entry.kind === 'language-analysis' && entry.data.fileEvidenceId === renamed.id)!; if (analysis.kind === 'language-analysis') assert.deepEqual(analysis.data.sources.map(item => item.path), ['view.tsx', 'renamed.tsx']);
}));

test('whole-file deletions retain before declarations; syntax errors and duplicate matching are explicit without invented identities', async () => fixture(async root => {
  const old = 'export function gone() { return 1; }\n'; await commit(root, 'deleted.ts', old); await writeFile(path.join(root, 'bad.ts'), 'function repeat(x: number): number;\nfunction repeat(x: string): string;\nfunction repeat(x: unknown) { return x; }\nexport function broken() { return 1; }\n'); git(root, 'add', '.'); git(root, 'commit', '-m', 'synthetic overloads'); git(root, 'rm', 'deleted.ts'); await writeFile(path.join(root, 'bad.ts'), 'function repeat(x: number): string;\nfunction repeat(x: string): number;\nfunction repeat(x: unknown) { return String(x); }\nexport function broken( {\n'); git(root, 'add', '.');
  const { bundle } = await collect(root); assert.equal(bundle.completeness.state, 'partial'); assert.ok(bundle.languageAnalysis.reasons.includes('SYMBOL_SYNTAX_ERROR')); assert.ok(bundle.languageAnalysis.reasons.includes('SYMBOL_MATCH_AMBIGUOUS')); const symbols = bundle.evidence.filter(entry => entry.kind === 'symbol'); assert.ok(symbols.some(entry => entry.data.name === 'gone' && entry.data.side === 'before')); assert.ok(!symbols.some(entry => entry.data.name === 'gone' && entry.data.side === 'after')); assert.ok(symbols.some(entry => entry.data.name === 'repeat' && entry.data.matching === 'ambiguous')); assert.ok(!symbols.some(entry => entry.data.name === 'repeat' && entry.data.counterpartOrdinal !== null)); assert.ok(!symbols.some(entry => entry.data.name === 'broken' && entry.data.side === 'after'));
}));

test('unsupported languages, source/patch bounds and changed working snapshots retain honest Git evidence', async () => fixture(async root => {
  await commit(root, 'sample.ts', 'export function sample() { return 1; }\n'); await writeFile(path.join(root, 'other.py'), 'def example(): return 1\n'); git(root, 'add', '.'); git(root, 'commit', '-m', 'synthetic unsupported language'); await writeFile(path.join(root, 'other.py'), 'def example(): return 2\n'); await writeFile(path.join(root, 'sample.ts'), 'export function sample() { return 2; }\n'); git(root, 'add', '.');
  const { bundle, repository } = await collect(root); assert.ok(bundle.languageAnalysis.reasons.includes('SYMBOL_LANGUAGE_UNSUPPORTED')); assert.ok(bundle.evidence.some(entry => entry.kind === 'file-change' && entry.data.destinationPath === 'other.py')); assert.ok(bundle.evidence.some(entry => entry.kind === 'symbol' && entry.data.name === 'sample'));
  const file = repository.comparisons[0]!.files.find(file => file.destinationPath === 'sample.ts')!; const result = file.languageAnalysis!; const limited = new TreeSitterAnalyzer().analyze({ sources: result.sources.map(snapshot => ({ snapshot, bytes: Buffer.from(`export function sample() { return ${snapshot.side === 'before' ? '1' : '2'}; }\n`) })), patch: file.patch!, maxSymbols: 1 }); assert.equal(limited.symbols.length, 1); assert.equal(limited.omittedSymbols, 1); assert.ok(limited.reasons.includes('SYMBOL_OUTPUT_LIMIT'));
  await writeFile(path.join(root, '.gitattributes'), 'sample.ts text eol=lf\n'); await writeFile(path.join(root, 'sample.ts'), 'export function sample() { return 3; }\r\n'); const normalized = await collect(root, 'unstaged'); assert.ok(normalized.bundle.languageAnalysis.reasons.includes('SYMBOL_PATCH_SOURCE_MISMATCH')); assert.ok(normalized.bundle.evidence.some(entry => entry.kind === 'hunk'));
  let patches = 0; const runner: GitRunner = async (...args) => { const result = await runGit(...args); if (args[1].includes('--patch')) { patches++; await writeFile(path.join(root, 'sample.ts'), `export function sample() { return ${patches + 3}; }\n`); } return result; };
  const unstable = await collect(root, 'unstaged', runner); assert.equal(unstable.repository.snapshot.consistency, 'inconsistent'); assert.equal(unstable.bundle.evidence.length, 0); assert.equal(unstable.bundle.languageAnalysis.state, 'unavailable');
}));

test('opt-in JSON/context validate syntax facts and citations; v0.1 defaults and locale-invariant IDs remain intact', async () => fixture(async root => {
  await commit(root, 'sample.ts', 'export const sample = () => 1;\n'); await writeFile(path.join(root, 'sample.ts'), 'export const sample = () => 2;\n'); git(root, 'add', '.');
  const plain = cli(root, 'evidence', '--json'); assert.equal(plain.status, 0); const v1 = JSON.parse(plain.stdout); assert.equal(v1.schemaVersion, '1.0.0'); assert.equal(v1.languageAnalysis, undefined);
  const en = cli(root, 'evidence', '--symbols', '--json', '--lang', 'en'), th = cli(root, 'evidence', '--symbols', '--json', '--lang', 'th'); assert.equal(en.status, 0, en.stderr); assert.equal(th.status, 0, th.stderr); assert.equal(en.stdout.trim().split('\n').length, 1); const bundle = validateSyntaxBundle(JSON.parse(en.stdout)); const other = validateSyntaxBundle(JSON.parse(th.stdout)); assert.deepEqual(bundle.evidence.map(entry => entry.id), other.evidence.map(entry => entry.id)); assert.deepEqual(bundle.evidence.slice(0, v1.evidence.length), v1.evidence);
  const context = cli(root, 'context', '--symbols', '--lang', 'th'); assert.equal(context.status, 0, context.stderr); assert.match(context.stdout, /v0.2/u); assert.match(context.stdout, /ไม่วิเคราะห์การอ้างอิงเชิงความหมาย/u); for (const symbol of bundle.evidence.filter(entry => entry.kind === 'symbol')) assert.ok(context.stdout.includes(`evidence:${symbol.id}`)); assert.match(renderContext(bundle, 'en').markdown, /not semantic identities/u);
  const limited = cli(root, 'evidence', '--symbols', '--json', '--max-file-bytes', '4'); assert.equal(limited.status, 1); const bounded = validateSyntaxBundle(JSON.parse(limited.stdout)); assert.ok(bounded.languageAnalysis.reasons.includes('SYMBOL_SOURCE_LIMIT')); assert.ok(bounded.evidence.some(entry => entry.kind === 'file-change'));
  const tampered = structuredClone(bundle); const entry = tampered.evidence.find(entry => entry.kind === 'symbol')!; if (entry.kind === 'symbol') { entry.data.hunkEvidenceIds[0] = '0'.repeat(64); entry.id = syntaxId(entry); tampered.languageAnalysis.evidenceIds = tampered.evidence.filter(entry => entry.kind === 'symbol' || entry.kind === 'language-analysis').map(entry => entry.id); } assert.throws(() => validateSyntaxBundle(tampered), { code: 'INTERNAL_CONTRACT_ERROR' });
}));

test('unborn staged additions have an explicit absent before side and syntax-only after observations', async () => fixture(async root => { await writeFile(path.join(root, 'new.ts'), 'export const added = () => 1;\n'); git(root, 'add', '.'); const { bundle } = await collect(root); assert.equal(bundle.languageAnalysis.state, 'complete'); const analysis = bundle.evidence.find(entry => entry.kind === 'language-analysis')!; if (analysis.kind === 'language-analysis') { assert.equal(analysis.data.sources[0]?.origin, 'absent'); assert.equal(analysis.data.sources[0]?.sha256, hash('')); assert.equal(analysis.data.sources[1]?.origin, 'git-blob'); } assert.ok(bundle.evidence.some(entry => entry.kind === 'symbol' && entry.data.side === 'after' && entry.data.name === 'added')); assert.ok(!bundle.evidence.some(entry => entry.kind === 'symbol' && entry.data.side === 'before')); }));

test('syntax schema is generated without replacing the v0.1 structural schema', async () => { const published = JSON.parse(await readFile(new URL('../../docs/syntax-evidence.schema.json', import.meta.url), 'utf8')); assert.deepEqual(published, z.toJSONSchema(syntaxOutputSchema, { target: 'draft-2020-12', io: 'input' })); });
