import { useEffect, useRef, useState } from 'react';
import { createRoot } from 'react-dom/client';
import type { UiSession, UiPage, UiRepository, UiFile, UiHunk, UiEvidence, UiInspection } from '../src/ui/contracts.js';
import './style.css';

const bootstrap = document.getElementById('difflearn-bootstrap')?.textContent;
const token: string | null = bootstrap ? (JSON.parse(bootstrap) as { token: string }).token : null;
async function api<T>(route: string, signal: AbortSignal): Promise<T> {
  if (!token) throw new Error('Session bootstrap is missing. Run dr ui --evidence <export.json>; a development server is not an evidence session.');
  const response = await fetch(route, { headers: { 'X-Difflearn-Session': token }, signal, cache: 'no-store', credentials: 'omit' });
  if (!response.ok) { const body = await response.json() as { error?: string }; throw new Error(body.error ?? `Viewer request failed (${response.status})`); }
  return response.json() as Promise<T>;
}
function useApi<T>(route: string | null) {
  const [result, setResult] = useState<{ key: string | null; data: T | null; error: string | null; loading: boolean }>({ key: null, data: null, error: null, loading: false });
  useEffect(() => {
    if (!route) return;
    const controller = new AbortController(); setResult({ key: route, data: null, error: null, loading: true });
    void api<T>(route, controller.signal).then(data => { if (!controller.signal.aborted) setResult({ key: route, data, error: null, loading: false }); }, error => { if (!controller.signal.aborted) setResult({ key: route, data: null, error: String(error.message), loading: false }); });
    return () => controller.abort();
  }, [route]);
  return result.key === route && route !== null ? result : { data: null, error: null, loading: route !== null };
}
const short = (value: string | null) => value ? `${value.slice(0, 12)}…` : 'unavailable';
const symbolName = (data: { name: string | null; kind: string; signatureDisplay?: string | undefined }) => data.signatureDisplay ?? data.name ?? data.kind;
type Text = (en: string, th: string) => string;
function Pager<T>({ page, change, text }: { page: UiPage<T>; change: (offset: number) => void; text: Text }) {
  return <div className="pager"><button disabled={!page.offset} onClick={() => change(Math.max(0, page.offset - page.limit))}>{text('Previous page', 'หน้าก่อน')}</button><span>{page.total ? `${page.offset + 1}–${Math.min(page.offset + page.limit, page.total)}` : '0'} / {page.total}</span><button disabled={page.offset + page.limit >= page.total} onClick={() => change(page.offset + page.limit)}>{text('Next page', 'หน้าถัดไป')}</button></div>;
}
type Line = UiHunk['data']['lines'][number];
function LineText({ line, text }: { line: Line | undefined; text: Text }) {
  if (!line) return <span aria-label={text('No line on this side', 'ไม่มีบรรทัดในด้านนี้')} />;
  return <><code>{line.content ?? text('[Text encoding unavailable; see evidence bytes]', '[ไม่สามารถแสดงข้อความ ดู bytes ในหลักฐาน]')}</code>{line.oldNoNewline || line.newNoNewline ? <span className="line-note">{text('No final newline', 'ไม่มี newline ท้ายไฟล์')}</span> : null}{line.content?.endsWith('\r') ? <span className="line-note">CRLF</span> : null}</>;
}
function splitLines(lines: Line[]) {
  const rows: { before?: Line; after?: Line }[] = [];
  for (let index = 0; index < lines.length;) {
    if (lines[index]!.kind === 'context') { const line = lines[index++]!; rows.push({ before: line, after: line }); continue; }
    const before: Line[] = [], after: Line[] = [];
    while (index < lines.length && lines[index]!.kind !== 'context') { const line = lines[index++]!; (line.kind === 'remove' ? before : after).push(line); }
    for (let ordinal = 0; ordinal < Math.max(before.length, after.length); ordinal++) rows.push({ ...(before[ordinal] ? { before: before[ordinal] } : {}), ...(after[ordinal] ? { after: after[ordinal] } : {}) });
  }
  return rows;
}
function Hunk({ hunk, split, selected, select, text }: { hunk: UiHunk; split: boolean; selected: boolean; select: () => void; text: Text }) {
  return <section className={`hunk ${selected ? 'selected' : ''}`} id={`hunk-${hunk.id}`} aria-label={`Hunk ${hunk.data.ordinal}`}>
    <button className="hunk-heading" aria-pressed={selected} onClick={select}><span className="mono">@@ -{hunk.data.oldStart},{hunk.data.oldCount} +{hunk.data.newStart},{hunk.data.newCount} @@</span><span>{hunk.data.heading ?? ''}</span><span>{text('Inspect', 'ตรวจหลักฐาน')}</span></button>
    <div className="code-scroll" tabIndex={0} aria-label={text('Collected hunk lines', 'บรรทัด hunk ที่เก็บรวบรวม')}>
      {split ? <div className="split-code"><div className="side-labels"><span>{text('Before', 'ก่อน')}</span><span>{text('After', 'หลัง')}</span></div>{splitLines(hunk.data.lines).map((row, ordinal) => <div className="split-row" key={ordinal}><div className={`code-side ${row.before?.kind ?? 'blank'}`}><span className="line-number">{row.before?.oldLine ?? ''}</span><div><LineText line={row.before} text={text} /></div></div><div className={`code-side ${row.after?.kind ?? 'blank'}`}><span className="line-number">{row.after?.newLine ?? ''}</span><div><LineText line={row.after} text={text} /></div></div></div>)}</div> : <div className="inline-code">{hunk.data.lines.map((line, ordinal) => <div className={`code-line ${line.kind}`} key={ordinal}><span className="line-number">{line.oldLine ?? ''}</span><span className="line-number">{line.newLine ?? ''}</span><span className="sign" aria-label={line.kind}>{line.kind === 'add' ? '+' : line.kind === 'remove' ? '−' : ' '}</span><div><LineText line={line} text={text} /></div></div>)}</div>}
    </div>
  </section>;
}
function App() {
  const [locale, setLocale] = useState('en'), [theme, setTheme] = useState('dark');
  const text: Text = (en, th) => locale === 'th' ? th : en;
  useEffect(() => { document.documentElement.dataset.theme = theme; document.documentElement.lang = locale; }, [theme, locale]);
  const session = useApi<UiSession>('/api/session');
  const [repositoryOffset, setRepositoryOffset] = useState(0), [repositoryId, setRepositoryId] = useState<string | null>(null);
  const repositories = useApi<UiPage<UiRepository>>(session.data ? `/api/repositories?offset=${repositoryOffset}` : null);
  const [query, setQuery] = useState(''), [change, setChange] = useState(''), [fileOffset, setFileOffset] = useState(0), [file, setFile] = useState<UiFile | null>(null);
  const files = useApi<UiPage<UiFile>>(repositoryId ? `/api/files?repositoryId=${repositoryId}&offset=${fileOffset}&q=${encodeURIComponent(query)}&change=${change}` : null);
  const [hunkOffset, setHunkOffset] = useState(0), [selectedId, setSelectedId] = useState<string | null>(null), [inspectOffset, setInspectOffset] = useState(0);
  const hunks = useApi<UiPage<UiHunk>>(file ? `/api/hunks?fileEvidenceId=${file.id}&offset=${hunkOffset}` : null);
  const inspection = useApi<UiInspection>(selectedId ? `/api/inspect?evidenceId=${selectedId}&offset=${inspectOffset}` : null);
  const [split, setSplit] = useState(false), [explorerOpen, setExplorerOpen] = useState(false), [inspectorOpen, setInspectorOpen] = useState(false);
  const [status, setStatus] = useState(''), [handoff, setHandoff] = useState(''); const heading = useRef<HTMLHeadingElement>(null);
  useEffect(() => { if (!repositoryId && repositories.data?.items[0]) setRepositoryId(repositories.data.items[0].repositoryId); }, [repositories.data, repositoryId]);
  useEffect(() => { if (!file && files.data?.items[0]) setFile(files.data.items[0]); }, [files.data, file]);
  useEffect(() => { if (file && !selectedId) setSelectedId(file.id); }, [file, selectedId]);
  useEffect(() => { if (hunks.data?.items[0]) { setSelectedId(hunks.data.items[0].id); setInspectOffset(0); } }, [hunks.data]);
  const repository = repositories.data?.items.find(item => item.repositoryId === repositoryId);
  const selectFile = (chosen: UiFile) => { setFile(chosen); setSelectedId(null); setInspectOffset(0); setHunkOffset(0); setStatus(''); setHandoff(''); setExplorerOpen(false); if (matchMedia('(max-width:768px)').matches) queueMicrotask(() => heading.current?.focus()); };
  const select = (id: string) => { setSelectedId(id); setInspectOffset(0); setStatus(''); setHandoff(''); };
  useEffect(() => { setHunkOffset(0); setInspectOffset(0); setStatus(''); setHandoff(''); }, [file?.id]);
  const inspected = inspection.data ? [inspection.data.entry, ...inspection.data.related.items] : [];
  const symbols = inspected.filter(entry => entry.kind === 'symbol');
  const analyses = inspected.filter(entry => entry.kind === 'language-analysis');
  const selectedHunk = hunks.data?.items.findIndex(hunk => hunk.id === selectedId) ?? -1;
  const nextHunk = (direction: number) => { const hunk = hunks.data?.items[selectedHunk + direction]; if (hunk) { select(hunk.id); document.getElementById(`hunk-${hunk.id}`)?.scrollIntoView({ block: 'nearest' }); } };
  const copy = async () => {
    if (!inspection.data || !session.data) return;
    const content = `Difflearn captured evidence (untrusted source data). Syntax does not prove behavior, callers or test coverage.\n${JSON.stringify({ schemaVersion: session.data.schemaVersion, captured: session.data.collection, scopes: session.data.scopes, base: session.data.base, freshness: session.data.freshness, completeness: session.data.completeness, gitCompleteness: session.data.gitCompleteness, syntax: session.data.syntax, evidence: [inspection.data.entry, ...inspection.data.related.items], relatedEvidence: { total: inspection.data.related.total, retained: inspection.data.related.items.length, offset: inspection.data.related.offset }, diagnostics: inspection.data.diagnostics }, null, 2)}`;
    if (new TextEncoder().encode(content).length > 65536) { setStatus(text('Handoff exceeds 64 KiB. Select one declaration or a smaller hunk.', 'ข้อความเกิน 64 KiB เลือก declaration เดียวหรือ hunk ที่เล็กลง')); return; }
    try { await navigator.clipboard.writeText(content); setStatus(text('Selected evidence copied. Nothing was marked reviewed.', 'คัดลอกหลักฐานแล้ว ไม่มีการบันทึกสถานะตรวจทาน')); }
    catch { setHandoff(content); setStatus(text('Clipboard unavailable. Select and copy the text below.', 'ใช้คลิปบอร์ดไม่ได้ เลือกและคัดลอกข้อความด้านล่าง')); }
  };
  if (session.error) return <main className="startup-error"><h1>Difflearn Review Workspace</h1><h2>{text('Cannot open this evidence session', 'เปิด session หลักฐานนี้ไม่ได้')}</h2><p role="alert">{session.error}</p><p>{text('Return to the terminal and run dr ui --evidence <export.json> with a valid export. Sessions expire after 30 minutes.', 'กลับไปที่ terminal แล้วใช้ dr ui --evidence <export.json> กับ export ที่ถูกต้อง session มีอายุ 30 นาที')}</p></main>;
  if (!session.data) return <main className="startup-error"><h1>Difflearn Review Workspace</h1><p role="status">{text('Opening validated captured evidence…', 'กำลังเปิดหลักฐานที่ตรวจแล้ว…')}</p></main>;
  const capture = session.data;
  return <>
    <a className="skip-link" href="#viewer">{text('Skip to hunks', 'ไปที่ hunks')}</a><a className="skip-link" href="#inspector" onClick={() => { setInspectorOpen(true); requestAnimationFrame(() => document.getElementById('inspector')?.focus()); }}>{text('Skip to inspector', 'ไปที่ inspector')}</a>
    <header className="topbar"><div className="brand"><span className="brand-mark" aria-hidden="true">D/</span><div><h1>Difflearn</h1><span>{text('Review Workspace', 'พื้นที่ตรวจทาน')}</span></div></div><div className="capture"><strong>{text('Captured export · Read-only', 'หลักฐานจาก export · อ่านอย่างเดียว')}</strong><span>{capture.schemaVersion !== '1.3.0' ? text('Historical schema', 'schema รุ่นก่อน') : text('Java syntax schema', 'schema ไวยากรณ์ Java')} {capture.schemaVersion} · {capture.collection.endedAt}</span><span>{text('Working-tree freshness not checked', 'ยังไม่ได้ตรวจความสดของ working tree')}</span></div><div className="preferences"><label>{text('Language', 'ภาษา')}<select aria-label={text('Language', 'ภาษา')} value={locale} onChange={event => setLocale(event.target.value)}><option value="en">English</option><option value="th">ไทย</option></select></label><button onClick={() => setTheme(theme === 'dark' ? 'light' : 'dark')}>{theme === 'dark' ? text('Light theme', 'ธีมสว่าง') : text('Dark theme', 'ธีมมืด')}</button></div></header>
    <div className="snapshot-bar"><span>{text('Scope', 'Scope')}: <strong>{capture.scopes.join(', ')}</strong></span><span>{text('Base', 'Base')}: <strong>{capture.base ?? text('Unavailable', 'ไม่มีข้อมูล')}</strong></span><span>Git: <strong>{capture.gitCompleteness.state}</strong></span><span>{text('Syntax', 'ไวยากรณ์')}: <strong>{capture.syntax.state}</strong></span><span>{text('References / tests / history', 'References / tests / history')}: {capture.discovery.references} / {capture.discovery.relatedTests} / {capture.discovery.history}</span></div>
    {capture.completeness.state !== 'complete' ? <div className="coverage-warning" role="status">{text('Partial or failed export. Retained evidence is shown; absence is not proof of no changes.', 'export ไม่ครบหรือมีส่วนล้มเหลว แสดงเฉพาะหลักฐานที่เก็บได้ การไม่มีข้อมูลไม่พิสูจน์ว่าไม่มีการเปลี่ยนแปลง')}<details><summary>{text('Coverage reasons', 'เหตุผลความไม่ครบถ้วน')}</summary><p>{capture.completeness.reasons.join(', ')}</p></details></div> : null}
    <nav className="region-controls" aria-label={text('Workspace regions', 'ส่วนของพื้นที่ตรวจทาน')}><button aria-controls="explorer" aria-expanded={explorerOpen} onClick={() => setExplorerOpen(!explorerOpen)}>{text('Repositories and files', 'Repositories และไฟล์')}</button><button aria-controls="inspector" aria-expanded={inspectorOpen} onClick={() => setInspectorOpen(!inspectorOpen)}>{text('Evidence inspector', 'ตรวจหลักฐาน')}</button></nav>
    <div className="workspace" data-explorer-open={explorerOpen} data-inspector-open={inspectorOpen}>
      <aside id="explorer" className="explorer" aria-label={text('Repository and file explorer', 'รายการ repository และไฟล์')}><h2>{text('Repositories', 'Repositories')} <span className="count">{capture.repositoryCount}</span></h2>
        {repositories.error ? <p role="alert">{repositories.error}</p> : null}{repositories.data ? <><ul className="repository-list">{repositories.data.items.map(item => <li key={item.repositoryId}><button className="repository-button" aria-pressed={repositoryId === item.repositoryId} onClick={() => { setRepositoryId(item.repositoryId); setFile(null); setSelectedId(null); setFileOffset(0); setQuery(''); setChange(''); }}><span>{item.path}</span><span className={`state ${item.state}`}>{item.state}</span></button></li>)}</ul><Pager page={repositories.data} change={offset => { setRepositoryOffset(offset); setRepositoryId(null); setFile(null); setSelectedId(null); setFileOffset(0); }} text={text} /></> : null}
        {repository ? <details className="repository-details"><summary>{text('Snapshot and revisions', 'Snapshot และ revisions')}</summary><p className="break">snapshot: {repository.snapshot.snapshotId ?? 'unavailable'}<br />HEAD: {repository.revisions?.head.oid ?? 'unavailable'}<br />merge-base: {repository.revisions?.mergeBase.oid ?? 'unavailable'}</p><p>{repository.reasons.join(', ')}</p></details> : null}
        <h2>{text('Changed files', 'ไฟล์ที่เปลี่ยน')} <span className="count">{files.data?.total ?? '…'}</span></h2><label className="filter">{text('Filter paths', 'ค้นหาพาธ')}<input value={query} maxLength={256} onChange={event => { setQuery(event.target.value); setFileOffset(0); setFile(null); setSelectedId(null); }} placeholder={text('Path or Thai identifier', 'พาธหรือชื่อภาษาไทย')} /></label><label className="filter">{text('Change type', 'ชนิดการเปลี่ยนแปลง')}<select aria-label={text('Change type', 'ชนิดการเปลี่ยนแปลง')} value={change} onChange={event => { setChange(event.target.value); setFileOffset(0); setFile(null); setSelectedId(null); }}><option value="">{text('All changes', 'ทั้งหมด')}</option>{['A', 'M', 'D', 'R', 'T'].map(kind => <option key={kind} value={kind}>{kind}</option>)}</select></label>
        {files.loading ? <p role="status">{text('Loading files…', 'กำลังโหลดไฟล์…')}</p> : null}{files.error ? <p role="alert">{files.error}</p> : null}{files.data ? <><ul className="file-list">{files.data.items.map(item => <li key={item.id}><button aria-pressed={file?.id === item.id} onClick={() => selectFile(item)}><span className="change-kind">{item.data.status}</span><span>{item.data.destinationPath ?? item.data.originalPath ?? '[path encoding unavailable]'}</span></button></li>)}</ul><Pager page={files.data} change={offset => { setFileOffset(offset); setFile(null); setSelectedId(null); }} text={text} /></> : null}
      </aside>
      <main id="viewer" className="viewer" tabIndex={-1}>
        {file ? <><div className="file-heading"><div><h2 ref={heading} tabIndex={-1}>{file.data.destinationPath ?? file.data.originalPath ?? '[path encoding unavailable]'}</h2>{file.data.status === 'R' ? <p>{text('Renamed from', 'เปลี่ยนชื่อจาก')} {file.data.originalPath}</p> : null}<p className="file-meta">{file.data.status} · {file.data.oldMode} → {file.data.newMode} · +{file.data.added ?? '?'} −{file.data.deleted ?? '?'}</p><p className="mono muted">snapshot {short(file.snapshotId)} / comparison {short(file.comparisonId)}</p></div><button onClick={() => { select(file.id); setInspectorOpen(true); }}>{text('File evidence', 'หลักฐานไฟล์')}</button></div>
          <div className="viewer-toolbar"><div className="segmented" aria-label={text('Hunk presentation', 'รูปแบบ hunk')}><button aria-pressed={!split} onClick={() => setSplit(false)}>{text('Inline', 'รวมบรรทัด')}</button><button aria-pressed={split} onClick={() => setSplit(true)}>{text('Split', 'แยกก่อน/หลัง')}</button></div><div className="hunk-navigation"><button disabled={selectedHunk <= 0} onClick={() => nextHunk(-1)}>{text('Previous hunk', 'hunk ก่อน')}</button><button disabled={!hunks.data || selectedHunk < 0 || selectedHunk >= hunks.data.items.length - 1} onClick={() => nextHunk(1)}>{text('Next hunk', 'hunk ถัดไป')}</button></div></div>
          <p className="collection-note">{text('Only collected hunks are shown. Source outside these ranges is not collected.', 'แสดงเฉพาะ hunks ที่เก็บรวบรวม ไม่ได้เก็บ source นอกช่วงเหล่านี้')}</p>
          {file.data.patch.state !== 'complete' ? <p className="coverage-warning">{text('Patch coverage', 'ความครบถ้วน patch')}: {file.data.patch.state}; {file.data.patch.reasons.join(', ')}. {text('Omitted hunks', 'hunks ที่ละไว้')}: {file.data.patch.omittedHunks ?? text('unknown', 'ไม่ทราบจำนวน')}</p> : null}
          {hunks.loading ? <p role="status">{text('Loading collected hunks…', 'กำลังโหลด hunks…')}</p> : null}{hunks.error ? <p role="alert">{hunks.error}</p> : null}
          {hunks.data ? <>{hunks.data.items.map((hunk, index) => <div key={hunk.id}>{index > 0 && (hunk.data.oldStart > hunks.data!.items[index - 1]!.data.oldStart + hunks.data!.items[index - 1]!.data.oldCount || hunk.data.newStart > hunks.data!.items[index - 1]!.data.newStart + hunks.data!.items[index - 1]!.data.newCount) ? <p className="uncollected-gap">{text('Uncollected source between hunks', 'ไม่ได้เก็บ source ระหว่าง hunks')}</p> : null}<Hunk hunk={hunk} split={split} selected={selectedId === hunk.id} select={() => { select(hunk.id); setInspectorOpen(true); }} text={text} /></div>)}{!hunks.data.total ? <div className="metadata-state"><h3>{file.data.binary ? text('Binary file', 'ไฟล์ binary') : file.data.kind === 'gitlink' ? 'Gitlink' : file.data.status === 'M' && file.data.oldMode !== file.data.newMode && file.data.added === 0 && file.data.deleted === 0 ? text('Mode-only change', 'เปลี่ยนเฉพาะ mode') : text('No collected text hunks', 'ไม่มี text hunks ที่เก็บรวบรวม')}</h3><p>{text('Inspect the modes, patch representation and coverage. No full source is reconstructed.', 'ตรวจ modes รูปแบบ patch และความครบถ้วน ไม่มีการสร้าง source file เต็มขึ้นมา')}</p><p>{file.data.patch.representation} / {file.data.patch.state}</p></div> : null}<Pager page={hunks.data} change={setHunkOffset} text={text} /></> : null}
        </> : <div className="empty-state"><span className="empty-mark" aria-hidden="true">D/</span><h2>{files.data?.total === 0 && capture.completeness.state === 'complete' && !query && !change ? text('No changes in this comparison', 'ไม่มีการเปลี่ยนแปลงใน comparison นี้') : text('Select retained evidence', 'เลือกหลักฐานที่เก็บรวบรวม')}</h2><p>{text('Choose a repository and file. Failed or omitted coverage is not a clean result.', 'เลือก repository และไฟล์ ส่วนที่ล้มเหลวหรือถูกละไว้ไม่ใช่ผลว่าไม่มีการเปลี่ยนแปลง')}</p>{repository?.state === 'failed' ? <p className="coverage-warning">{repository.reasons.join(', ')}</p> : null}{!capture.repositoryCount ? <p>{text('No repositories retained in this export. Check the export coverage.', 'ไม่มี repository ที่เก็บไว้ใน export นี้ ตรวจความครบถ้วนของ export')}</p> : null}</div>}
      </main>
      <aside id="inspector" className="inspector" tabIndex={-1} aria-label={text('Evidence inspector', 'ตรวจหลักฐาน')}><div className="inspector-heading"><h2>{text('Evidence inspector', 'ตรวจหลักฐาน')}</h2><button className="inspector-close" onClick={() => setInspectorOpen(false)}>{text('Close', 'ปิด')}</button></div><p className="syntax-policy">{text('Syntax only. No behavior, semantic callers or test coverage is proved.', 'ไวยากรณ์เท่านั้น ไม่พิสูจน์พฤติกรรม ผู้เรียกเชิงความหมาย หรือ test coverage')}</p>
        {inspection.loading ? <p role="status">{text('Loading evidence…', 'กำลังโหลดหลักฐาน…')}</p> : null}{inspection.error ? <p role="alert">{inspection.error}</p> : null}{inspection.data ? <><div className="selected-evidence"><span>{inspection.data.entry.kind}</span><code className="break">{inspection.data.entry.id}</code></div>
          <h3>{text('Declarations', 'Declarations')}</h3>{symbols.length ? <ul className="symbol-list">{symbols.map(symbol => <li key={symbol.id}><button onClick={() => select(symbol.id)}><strong>{symbolName(symbol.data)}</strong><span>{symbol.data.language} / {symbol.data.kind} / {symbol.data.side}</span><span>{text('Lines', 'บรรทัด')} {symbol.data.range.startLine}–{symbol.data.range.endLine}; {text('bytes', 'bytes')} {symbol.data.range.startByte}–{symbol.data.range.endByte}</span><span className={symbol.data.matching === 'ambiguous' ? 'warning-text' : ''}>{symbol.data.matching === 'candidate' ? text('Syntactic candidate', 'ตัวเลือกจับคู่เชิงไวยากรณ์') : symbol.data.matching}</span><span>{symbol.data.scope.map(scope => scope.name ?? `[${scope.kind}]`).join(' / ')}</span></button></li>)}</ul> : <p className="muted">{capture.syntax.state === 'not-requested' ? text('Syntax not requested in this export. Export with --symbols for Java declarations.', 'export นี้ไม่ได้ขอ syntax ใช้ --symbols เพื่อเก็บ Java declarations') : text('No linked declarations retained for this selection/page. Check syntax coverage.', 'ไม่มี declarations ที่เชื่อมกับรายการ/หน้านี้ ตรวจความครบถ้วน syntax')}</p>}
          {analyses.map(analysis => <details key={analysis.id} open={analysis.data.state !== 'complete'}><summary>{text('Language coverage', 'ความครบถ้วนภาษา')}: {analysis.data.state}</summary><p>{analysis.data.reasons.join(', ') || text('No recorded syntax limitations', 'ไม่มีข้อจำกัด syntax ที่บันทึกไว้')}</p><p>{text('Unmapped changed lines / omitted symbols', 'บรรทัดที่ map ไม่ได้ / symbols ที่ละไว้')}: {analysis.data.unmappedChangedLines} / {analysis.data.omittedSymbols}</p>{analysis.data.sources.map(side => <p key={side.side} className="break">{side.side}: {side.language ?? 'unsupported'} / {side.origin} / {side.state}<br />{side.path}<br />SHA-256 {side.sha256 ?? 'unavailable'}<br />{side.reason}</p>)}</details>)}
          <Pager page={inspection.data.related} change={setInspectOffset} text={text} /><details><summary>{text('Selected record and provenance', 'รายการที่เลือกและ provenance')}</summary><pre className="evidence-json">{JSON.stringify(inspection.data.entry, null, 2)}</pre></details>
          <h3>{text('Diagnostics', 'Diagnostics')}</h3>{inspection.data.diagnostics.length ? inspection.data.diagnostics.map((diagnostic, index) => <p key={index} className="diagnostic"><strong>{diagnostic.code}</strong><br />{diagnostic.message}</p>) : <p className="muted">{text('No recorded diagnostics for this selection', 'ไม่มี diagnostics ที่บันทึกสำหรับรายการนี้')}</p>}
          <button className="copy-button" onClick={() => void copy()}>{text('Copy selected evidence', 'คัดลอกหลักฐานที่เลือก')}</button><p className="handoff-status" role="status">{status}</p>{handoff ? <label>{text('Selectable handoff text', 'ข้อความสำหรับเลือกคัดลอก')}<textarea readOnly value={handoff} rows={10} /></label> : null}
        </> : <p>{text('Select a file, hunk or declaration to inspect its original evidence.', 'เลือกไฟล์ hunk หรือ declaration เพื่อดูหลักฐานต้นฉบับ')}</p>}
      </aside>
    </div><footer className="session-footer">{text('Captured evidence only. Review writes and live refresh are not enabled.', 'อ่านหลักฐานจาก export เท่านั้น ยังไม่เปิดการเขียน review state หรือ live refresh')} · {text('Session expires', 'session หมดอายุ')}: {capture.expiresAt}</footer>
  </>;
}
createRoot(document.getElementById('root')!).render(<App />);
