import { z } from 'zod';
import { ScanError } from '../config/load.js';
import { digest } from '../git/snapshot.js';
import { syntaxBundleSchema, syntaxEvidenceSchema, syntaxOutputSchema, validateSyntaxBundle, type SyntaxBundle, type SyntaxEvidence } from './syntax.js';

const uint = z.number().int().nonnegative().max(Number.MAX_SAFE_INTEGER), positive = uint.min(1), hash = z.string().regex(/^[a-f0-9]{64}$/u), oid = z.string().regex(/^(?:[a-f0-9]{40}|[a-f0-9]{64})$/u), code = z.string().regex(/^[A-Z][A-Z0-9_]*$/u);
export const discoveryRequestSchema = z.strictObject({ references: z.boolean(), relatedTests: z.boolean(), history: z.boolean(), maxSymbols: positive.max(256), maxResults: positive.max(1000), maxHistory: positive.max(200) });
export const contentSnapshotSchema = z.strictObject({ repositoryId: hash, snapshotId: hash, comparisonId: hash, corpusId: hash, path: z.string(), pathBytes: z.string().min(1), origin: z.enum(['git-blob', 'filesystem']), endpoint: z.enum(['commit', 'index', 'working-tree']), oid: oid.nullable(), sha256: hash, byteLength: uint });
const location = z.strictObject({ content: contentSnapshotSchema, startByte: uint, endByte: uint, line: positive, startColumn: uint, endColumn: uint });
const queryResult = z.strictObject({ symbolEvidenceId: hash, query: z.string(), searchRule: z.literal('case-sensitive-fixed-substring'), corpusIds: z.array(hash), outcome: z.enum(['matches', 'no-matches', 'missing-rg', 'execution-error', 'truncated']), reasons: z.array(code), observedMatches: uint, retainedMatches: uint, omittedMatches: uint.nullable(), sameNameSymbolIds: z.array(hash) });
const relatedResult = z.strictObject({ symbolEvidenceId: hash, query: z.string(), outcome: z.enum(['candidates', 'no-candidates', 'partial', 'unavailable']), reasons: z.array(code), retainedCandidates: uint, omittedCandidates: uint.nullable(), testExecution: z.literal('not-run') });
const historyResult = z.strictObject({ fileEvidenceId: hash, outcome: z.enum(['commits', 'no-commits', 'unborn', 'execution-error', 'truncated']), headOid: oid.nullable(), paths: z.array(z.string()).min(1), arguments: z.array(z.string()), commits: z.array(z.strictObject({ oid, parents: z.array(oid) })), truncated: z.boolean(), shallow: z.boolean(), reasons: z.array(code), querySemantics: z.literal('pinned-head-reachable-literal-path-history-no-follow-topological-order'), runtimeBehavior: z.literal('not-inferred') });
const source = z.strictObject({ kind: z.literal('candidate-discovery'), method: z.enum(['rg-fixed-string', 'test-heuristic', 'git-path-history']), executed: z.boolean(), arguments: z.array(z.array(z.string())), originatingEvidenceIds: z.array(hash) });
const common = { ...syntaxEvidenceSchema.options[0].shape, source, confidence: z.enum(['fact', 'candidate']) };
const referenceQuery = z.strictObject({ ...common, kind: z.literal('reference-query'), data: queryResult, confidence: z.literal('fact') });
const reference = z.strictObject({ ...common, kind: z.literal('reference-candidate'), data: z.strictObject({ symbolEvidenceId: hash, queryEvidenceId: hash, query: z.string(), location, crossRepository: z.boolean(), interpretation: z.literal('text-match-not-confirmed-reference') }), confidence: z.literal('candidate') });
const testQuery = z.strictObject({ ...common, kind: z.literal('related-test-query'), data: relatedResult, confidence: z.literal('fact') });
const test = z.strictObject({ ...common, kind: z.literal('related-test-candidate'), data: z.strictObject({ symbolEvidenceId: hash, queryEvidenceId: hash, query: z.string(), content: contentSnapshotSchema, range: z.strictObject({ startByte: uint, endByte: uint, line: positive }).nullable(), heuristic: z.array(z.enum(['test-filename', 'test-call-syntax', 'same-file-stem', 'symbol-name-in-filename', 'fixed-string-symbol-text', 'relative-import-syntax'])).min(1), importHints: z.array(z.strictObject({ kind: z.enum(['import', 'test-call']), text: z.string(), startByte: uint, endByte: uint, line: positive })), crossRepository: z.boolean(), testExecution: z.literal('not-run'), interpretation: z.literal('potential-test-no-coverage-conclusion') }), confidence: z.literal('candidate') });
const history = z.strictObject({ ...common, kind: z.literal('history'), data: historyResult, confidence: z.literal('fact') });
export const candidateEvidenceSchema = z.discriminatedUnion('kind', [...syntaxEvidenceSchema.options, referenceQuery, reference, testQuery, test, history]);
export type CandidateEvidence = z.infer<typeof candidateEvidenceSchema>;
const component = z.strictObject({ requested: z.boolean(), state: z.enum(['not-requested', 'complete', 'partial', 'unavailable']), reasons: z.array(code), queriesRequested: uint, queriesCollected: uint, omittedQueries: uint, evidenceIds: z.array(hash) });
export const candidateBundleSchema = syntaxBundleSchema.extend({ schemaVersion: z.literal('1.2.0'), evidence: z.array(candidateEvidenceSchema), analysis: z.strictObject({ policy: z.literal('git-syntax-and-candidate-facts'), unsupported: z.array(z.string()) }), discoveryAnalysis: z.strictObject({ request: discoveryRequestSchema, limits: z.strictObject({ maxCorpusFiles: positive, maxCorpusBytes: positive, maxFileBytes: positive, maxQueryBytes: positive, queryTimeoutMs: positive, analysisTimeoutMs: positive }), corpus: z.strictObject({ state: z.enum(['not-requested', 'complete', 'partial']), reasons: z.array(code), snapshotIds: z.array(hash), files: z.array(contentSnapshotSchema), excludedFiles: uint, omittedFiles: uint }), references: component, relatedTests: component, history: component, syntaxCompleteness: syntaxBundleSchema.shape.completeness }) });
export type CandidateBundle = z.infer<typeof candidateBundleSchema>;
export const candidateOutputSchema = z.union([syntaxOutputSchema, candidateBundleSchema]);
export const isCandidateKind = (kind: string) => ['reference-query', 'reference-candidate', 'related-test-query', 'related-test-candidate', 'history'].includes(kind);
export function candidateId(entry: Pick<CandidateEvidence, 'repositoryId' | 'snapshotId' | 'comparisonId' | 'kind' | 'subject' | 'data'>) { return digest(['evidence-v1', entry.repositoryId, entry.comparisonId ?? entry.snapshotId, entry.kind, entry.subject, entry.data]); }
export function validateCandidateBundle(value: unknown): CandidateBundle {
  const parsed = candidateBundleSchema.safeParse(value); if (!parsed.success) throw new ScanError('INTERNAL_CONTRACT_ERROR', 'Candidate bundle violated its runtime schema', 1);
  const bundle = parsed.data, fail = (condition: unknown) => { if (!condition) throw new ScanError('INTERNAL_CONTRACT_ERROR', 'Candidate references or provenance violated their contract', 1); };
  const { discoveryAnalysis: _discovery, ...projection } = bundle;
  const syntax = validateSyntaxBundle({ ...projection, schemaVersion: '1.1.0', evidence: bundle.evidence.filter(entry => !isCandidateKind(entry.kind)), completeness: bundle.discoveryAnalysis.syntaxCompleteness, analysis: { policy: 'git-and-syntax-facts', unsupported: bundle.analysis.unsupported.includes('history') ? bundle.analysis.unsupported : [...bundle.analysis.unsupported, 'history'] } });
  const entries = new Map(bundle.evidence.map(entry => [entry.id, entry])); const contents = new Map(bundle.discoveryAnalysis.corpus.files.map(content => [digest(content), content]));
  fail(entries.size === bundle.evidence.length && bundle.completeness.collectedEvidence === entries.size);
  const expectedUnsupported = ['references', 'behavior', 'return-types', 'impact', 'test-coverage', 'history', 'review-state'].filter(kind => !bundle.discoveryAnalysis.request.history || kind !== 'history');
  fail(bundle.analysis.unsupported.length === expectedUnsupported.length && expectedUnsupported.every(kind => bundle.analysis.unsupported.includes(kind)));
  fail(bundle.discoveryAnalysis.corpus.files.length <= bundle.discoveryAnalysis.limits.maxCorpusFiles && bundle.discoveryAnalysis.corpus.files.reduce((sum, file) => sum + file.byteLength, 0) <= bundle.discoveryAnalysis.limits.maxCorpusBytes);
  const queries = new Map<string, CandidateEvidence[]>();
  for (const entry of bundle.evidence) if (entry.kind === 'reference-candidate' || entry.kind === 'related-test-candidate') { const group = queries.get(entry.data.queryEvidenceId) ?? []; group.push(entry); queries.set(entry.data.queryEvidenceId, group); }
  const validateContent = (content: z.infer<typeof contentSnapshotSchema>) => {
    fail(contents.has(digest(content))); const repo = bundle.repositories.find(repo => repo.repositoryId === content.repositoryId);
    fail(repo?.snapshot.snapshotId === content.snapshotId && repo.comparisons.some(comparison => comparison.comparisonId === content.comparisonId));
    fail(Buffer.from(content.pathBytes, 'base64').toString('utf8') === content.path && Buffer.from(content.pathBytes, 'base64').toString('base64') === content.pathBytes && bundle.discoveryAnalysis.corpus.snapshotIds.includes(content.corpusId));
    fail(content.path.length > 0 && !content.path.startsWith('/') && !content.path.split('/').some(part => part === '' || part === '.' || part === '..') && content.byteLength <= bundle.discoveryAnalysis.limits.maxFileBytes);
    fail(content.origin === 'filesystem' ? content.oid === null && content.endpoint === 'working-tree' : content.oid !== null && content.endpoint !== 'working-tree');
  };
  for (const content of bundle.discoveryAnalysis.corpus.files) validateContent(content);
  for (const corpusId of bundle.discoveryAnalysis.corpus.snapshotIds) { const files = bundle.discoveryAnalysis.corpus.files.filter(content => content.corpusId === corpusId); if (files.length) fail(corpusId === digest(['candidate-corpus-v1', files[0]!.repositoryId, files[0]!.snapshotId, files[0]!.comparisonId, files.map(content => ({ ...content, corpusId: '' }))])); }
  for (const entry of bundle.evidence) {
    if (!isCandidateKind(entry.kind)) continue;
    fail(candidateId(entry) === entry.id); const repo = bundle.repositories.find(repo => repo.repositoryId === entry.repositoryId); fail(repo?.snapshot.snapshotId === entry.snapshotId && repo.comparisons.some(comparison => comparison.comparisonId === entry.comparisonId));
    for (const id of entry.source.originatingEvidenceIds) fail(entries.has(id) && id !== entry.id);
    if (entry.kind === 'history') { const file = entries.get(entry.data.fileEvidenceId); fail(file?.kind === 'file-change' && file.repositoryId === entry.repositoryId && file.comparisonId === entry.comparisonId && entry.source.originatingEvidenceIds.includes(file.id)); fail(entry.data.headOid === repo?.revisions?.head.oid); fail(entry.data.paths.every(path => path === (file?.kind === 'file-change' ? file.data.originalPath : null) || path === (file?.kind === 'file-change' ? file.data.destinationPath : null))); fail(entry.data.commits.length <= bundle.discoveryAnalysis.request.maxHistory && entry.source.method === 'git-path-history'); fail(entry.data.outcome !== 'unborn' || entry.data.headOid === null && entry.data.commits.length === 0); fail(entry.data.outcome !== 'no-commits' || entry.data.commits.length === 0); fail(entry.data.truncated === (entry.data.outcome === 'truncated')); fail(digest(entry.source.arguments) === digest([entry.data.arguments])); continue; }
    if (entry.kind === 'reference-query' || entry.kind === 'related-test-query' || entry.kind === 'reference-candidate' || entry.kind === 'related-test-candidate') {
      const symbol = entries.get(entry.data.symbolEvidenceId); fail(symbol?.kind === 'symbol' && symbol.repositoryId === entry.repositoryId && symbol.snapshotId === entry.snapshotId && symbol.comparisonId === entry.comparisonId && entry.data.query === symbol.data.name);
      fail(entry.source.originatingEvidenceIds.includes(entry.data.symbolEvidenceId));
      if (entry.kind === 'reference-query') { fail(entry.source.method === 'rg-fixed-string' && entry.data.retainedMatches === (queries.get(entry.id)?.length ?? 0) && entry.data.retainedMatches <= bundle.discoveryAnalysis.request.maxResults && entry.data.observedMatches >= entry.data.retainedMatches); fail(entry.data.outcome !== 'no-matches' || entry.data.retainedMatches === 0); fail(digest(entry.data.corpusIds) === digest(bundle.discoveryAnalysis.corpus.snapshotIds)); for (const id of entry.data.sameNameSymbolIds) { const other = entries.get(id); fail(other?.kind === 'symbol' && other.data.name === entry.data.query); } }
      if (entry.kind === 'related-test-query') { fail(entry.source.method === 'test-heuristic' && entry.data.retainedCandidates === (queries.get(entry.id)?.length ?? 0) && entry.data.retainedCandidates <= bundle.discoveryAnalysis.request.maxResults); fail(entry.data.outcome !== 'no-candidates' || entry.data.retainedCandidates === 0); }
      if (entry.kind === 'reference-candidate' || entry.kind === 'related-test-candidate') {
        const query = entries.get(entry.data.queryEvidenceId); fail(query?.kind === (entry.kind === 'reference-candidate' ? 'reference-query' : 'related-test-query') && 'symbolEvidenceId' in query.data && query.data.symbolEvidenceId === entry.data.symbolEvidenceId && entry.source.originatingEvidenceIds.includes(query.id));
        const content = entry.kind === 'reference-candidate' ? entry.data.location.content : entry.data.content; validateContent(content); fail(entry.data.crossRepository === (content.repositoryId !== entry.repositoryId));
        const range = entry.kind === 'reference-candidate' ? entry.data.location : entry.data.range; if (range) fail(range.startByte <= range.endByte && range.endByte <= content.byteLength);
        if (entry.kind === 'related-test-candidate') for (const hint of entry.data.importHints) fail(hint.startByte <= hint.endByte && hint.endByte <= content.byteLength);
      }
    }
  }
  for (const name of ['references', 'relatedTests', 'history'] as const) {
    const state = bundle.discoveryAnalysis[name], queryKind = name === 'references' ? 'reference-query' : name === 'relatedTests' ? 'related-test-query' : 'history';
    fail(state.requested === bundle.discoveryAnalysis.request[name] && state.queriesRequested === state.queriesCollected + state.omittedQueries && state.queriesCollected === bundle.evidence.filter(entry => entry.kind === queryKind).length);
    fail(digest(state.evidenceIds) === digest(bundle.evidence.filter(entry => entry.kind === queryKind || name === 'references' && entry.kind === 'reference-candidate' || name === 'relatedTests' && entry.kind === 'related-test-candidate').map(entry => entry.id)));
    fail(state.state !== 'complete' || state.reasons.length === 0 && state.omittedQueries === 0); fail(state.requested || state.state === 'not-requested' && state.queriesRequested === 0);
    fail(state.queriesCollected <= bundle.discoveryAnalysis.request.maxSymbols); fail(state.state !== 'partial' && state.state !== 'unavailable' || state.reasons.length > 0 || state.omittedQueries > 0);
  }
  fail(digest(syntax.languageAnalysis) === digest(bundle.languageAnalysis)); return bundle;
}
export function candidateProjection(base: SyntaxBundle, request: z.infer<typeof discoveryRequestSchema>) { return { ...base, schemaVersion: '1.2.0' as const, analysis: { policy: 'git-syntax-and-candidate-facts' as const, unsupported: base.analysis.unsupported.filter(kind => !request.history || kind !== 'history') } }; }
